apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tke-auth-server-cert
  namespace: tke
spec:
  secretName: tke-auth-server-secret
  duration: 87600h
  renewBefore: 87590h
  subject:
    organizations:
    - Tencent
  commonName: TKE-SERVER
  isCA: false
  usages:
    - server auth
    - client auth
  dnsNames:
  {{- with .Values.certificate.dnsNames }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  uris: 
  {{- with .Values.certificate.uris }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  ipAddresses: 
  {{- with .Values.certificate.ipAddresses }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  issuerRef:
    name: ca-issuer